internal enum _SoundModifier: Sendable {
    case oneShot
    case rhythm(RhythmPattern, MusicalTime, SoundSourceAnchor)
    case offset(MusicalTime)
    case repeated(Int)
    case fast(UInt64)
    case slow(UInt64)
    case notes([Pitch], SoundSourceAnchor)
    case notePattern(NotePattern, MusicalTime, SoundSourceAnchor)
    case transpose(Int)
    case pitchPattern(PitchPattern, MusicalTime)
    case chord(Chord)
    case dynamic(Dynamic)
    case velocity(Int)
    case gate(Double)
    case staccato
    case tuning(Tuning)
    case envelope(Envelope)
    case pitchEnvelope(EnvelopeModulation)
    case filterEnvelope(EnvelopeModulation)
    case fixedFilter(FilterKind, Frequency, Double, FilterSlope)
    case cutoffPattern(FilterKind, CutoffPattern, MusicalTime, Double, FilterSlope)
    case envelopePattern(EnvelopePattern, MusicalTime)
    case sampleSelection(SampleSelectionPattern, MusicalTime)
    case sampleRegion(SampleRegion)
    case sampleReversed
    case samplePlaybackRate(Double)
    case unison(Unison)
    case voicePolicy(VoicePolicy)
    case chokeGroup(String)
    case effect(AudioEffect)
    case gain(Double)
    case gainPattern(GainPattern, MusicalTime)
    case pan(Double)
    case panPattern(PanPattern, MusicalTime)
    case muted
    case send(String, Double)
    case output(String)
}
